### ISSUE TITLE
Segmentation fault when running bsdiff4 on smail files

### ISSUE THREAD

**Issue by sagiben** [ilanschnell/bsdiff4#14] opened 2019-11-19 20:32 UTC
This test case is simple and happens with versions 1.1.7 and 1.1.8
This test case pass with 1.1.6 and a patch is generated

```
$ bsdiff4 file.1 file.2 patch
Segmentation fault
```

the content of those files are :
```
$ hexdump -C file.1 
00000000  31 32 33 34 35 36 37 38  39 20 39 38 37 36 35 34  |123456789 987654|
00000010  33 32 31                                          |321|
00000013
$ hexdump -C file.2
00000000  31 32 33 34 35 36 37 38  39 30 30 30 39 38 37 36  |1234567890009876|
00000010  35 34 33 32 31                                    |54321|
00000015
```

**Comment by sagiben** [comment] 2019-11-20 10:15
hi, reverting this commit : https://github.com/ilanschnell/bsdiff4/commit/35a390c67bb5c07b01b3d7b271e354da7fb36952

solves this issue

**Comment by ilanschnell** [comment] 2019-11-20 19:14
Thanks!  I'm not able to reproduce this issue myself.  Defining `PY_SSIZE_T_CLEAN`, caused #13 which I fixed in d10e76af3797c6265c86bc3d3b6a0e5b2e7faf14.  So I hope that this commit fixes this issue.  Can you confirm that the problem is now fixed?

**Comment by sagiben** [comment] 2019-11-20 20:08
verified as fixed with https://github.com/ilanschnell/bsdiff4/commit/d10e76af3797c6265c86bc3d3b6a0e5b2e7faf14

**Comment by ilanschnell** [comment] 2019-11-20 20:35
Thank you for verifying!  I will release a new version now.

**Closed by ilanschnell** 2019-11-20 20:35 UTC
